apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: oilja340s-python-gitops
  description: This is GitOps manifest for oilja340s-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: oilja340s-python
    backstage.io/kubernetes-id: oilja340s-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: oilja340s-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:oilja340s-python
